### ISSUE TITLE
default value of if flag not working

### ISSUE THREAD

**Issue by arastu** [cafebazaar/blacksmith#42]
[this](https://github.com/cafebazaar/blacksmith/blob/master/blacksmith.go#L43)

**Comment by remohammadi** [comment]
Can you please add more details? Is there any error message? log messages?

**Comment by arastu** [comment]
"If" flags default value is "0.0.0.0", this is cause error when pass to `net.InterfaceByName` function.
Is "if" flags optional? 
if not i think show error to set "if" flag is required.

**Comment by remohammadi** [comment]
Pull request is welcomed ;)

**Comment by arastu** [comment]
ok :)
